# version: '3.8'
services:
  axolotl:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/workspace/axolotl
      - /models/huggingface/:/root/.cache/huggingface/ # cache huggingface models
    # set environment variables
    environment:
      # Set environment variables
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME}
      - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL}
      - WANDB_API_KEY=${WANDB_API_KEY}
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              capabilities: [gpu]
    command: tail -f /dev/null
